### ISSUE TITLE
WriterReaderPhaser

### ISSUE THREAD

**Issue by QuietMisdreavus** [QuietMisdreavus/synchronoise#1]
[Suggested](https://twitter.com/runswithbricks/status/836785520545951744) by @runswithbricks on Twitter.

[Here's a link to a javadoc page for it](https://hdrhistogram.github.io/HdrHistogram/JavaDoc/org/HdrHistogram/WriterReaderPhaser.html).

If I'm understanding this correctly, this allows a certain pattern of access:

* Any number of threads can enter "writer critical sections" at once.
* Threads that attempt to obtain a "reader lock" mutually exclude any other thread from doing so.
* A thread that holds a "reader lock" can "flip the phase" of the WriterReaderPhaser, thus waiting for all currently-active "writer critical sections" to finish.

The original class doesn't guard any data itself, but it may be worthwhile to figure out how to wrap some arbitrary data for this, a la Mutex and friends from std. The pattern of allowing multiple *writers* but one *reader* seems strange from a Rust perspective, when thinking about things like aliased mutable references. On the other hand, it also sounds similar to the mpsc channels in std, just with some synchronization around its access.

Perhaps this statement from the class description helps figure out adaptation possibilities:

> While a WriterReaderPhaser can be useful in multiple scenarios, a specific and common use case is that of safely managing "double buffered" data stream access in which writers can proceed without being blocked, while readers gain access to stable and unchanging buffer samples

...but I think I can work out a data-less version easily enough, especially if I build off the existing CountdownEvent.

**Comment by marshallpierce** [comment]
There's more context here: https://stuff-gil-says.blogspot.com/2014/11/writerreaderphaser-story-about-new.html

A very useful example of how this is used is in [Recorder](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/Recorder.java): allow concurrent writes to the "hot" buffer, and occasionally switch it with the "cold" buffer so that a logging thread can safely read out of the formerly-hot buffer at its leisure, all with no locks.

**Comment by QuietMisdreavus** [comment]
Thanks for the link, that was really helpful!

While I was going over it, I couldn't stop thinking about what happens if writers enter their critical sections while a reader is waiting for the phase to flip. Since the user of a WriterReaderPhaser is intended to also coordinate the swap, it makes more sense. Now that I'm thinking about it, my initial thought of using a single CountdownEvent to coordinate the wait won't quite work the same way, so I'll have to think on it some more. I'll let you know if/when I get something put together.

On the other hand, a CountdownEvent wouldn't be acceptable for performance reasons anyway, since it keeps a Mutex<isize> for its counter that needs to be locked when a thread modifies the count. I'll probably copy the "atomic counter + spin-lock when flipping" method for the initial implementation, since Condvar requires a Mutex to lock. That way I can keep the same performance/locking guarantees, which seem to be a major influence on its design.

**Comment by QuietMisdreavus** [comment]
I [just committed](https://github.com/QuietMisdreavus/synchronoise/commit/f4eb498d64a086ee1e799c0492e25d67cedcc34d) an initial port of WriterReaderPhaser. I'm a little wary of the orderings i gave to the atomic loads/stores, but the basic structure should be there.

**Comment by QuietMisdreavus** [comment]
I've gone ahead and published 0.3.0 with this port in it. If you find issues with it, let me know, otherwise, I'm closing this as being finished.

**Comment by marshallpierce** [comment]
Thanks, I'll use it when I implement Recorder!
